language: cpp

services:
  - docker

before_script:

  - docker build -t blumamir/time-sync-server .

  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..
  - cd ..

script:
  - make -C build

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push blumamir/time-sync-server
  on:
    branch: master
